version: '3.8'

services:
  newsletter-api:
    build: .
    container_name: newsletter-api
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - BREVO_API_KEY=${BREVO_API_KEY}
      - BREVO_SENDER_EMAIL=${BREVO_SENDER_EMAIL}
      - DATABASE_URL=${DATABASE_URL}
      - SEND_SECRET=${SEND_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=9000
    networks:
      - newsletter-network

networks:
  newsletter-network:
    driver: bridge
